services:
  bot:
    build:
      context: .
    restart:
      unless-stopped
    volumes:
      - ./data:/app/data
      - ./src/log/archive:/app/src/log/archive
      - ./.secrets.toml:/app/.secrets.toml:ro
      - ./credentials.json:/app/credentials.json:ro
